<?php use App\Helpers\InventoryPresentation as ItemUI;

$metrics = [
    ['Total barang','Jenis barang','box','/barang','SKU tercatat'],
    ['Total stok','Unit tersedia','warehouse','/reports','Saldo inventori saat ini'],
    ['Masuk bulan ini','Masuk bulan ini','in','/barang-masuk','Unit diterima'],
    ['Keluar bulan ini','Keluar bulan ini','out','/barang-keluar','Unit digunakan'],
    ['Stok rendah','Stok rendah','alert','/barang?status=low','Di bawah / sama minimum'],
    ['Stok habis','Stok habis','box','/barang?status=out','Perlu pengadaan'],
];
?>
<div class="page-heading"><div><div class="eyebrow">RINGKASAN INVENTORI</div><h1>Semua stok, dalam kendali.</h1><p>Pantau persediaan, pahami pergerakan, dan tindak lanjuti kebutuhan barang.</p></div><a class="btn btn-primary" href="/barang-masuk/create"><?= icon('plus') ?> Catat barang masuk</a></div>
<div class="overview-banner"><div><span class="status-dot"></span><strong>Ringkasan workspace</strong><span><?= (int) $cards['Kategori'] ?> kategori</span><span><?= (int) $cards['Gudang'] ?> gudang</span><span><?= (int) $cards['Supplier'] ?> supplier</span></div><a href="/reports">Buka laporan <?= icon('arrow') ?></a></div>
<section class="metric-grid" aria-label="Statistik inventori">
<?php foreach ($metrics as [$key,$label,$symbol,$url,$caption]): ?>
    <a href="<?= e($url) ?>" class="metric <?= $key === 'Stok rendah' ? 'metric-warning' : ($key === 'Stok habis' ? 'metric-danger' : '') ?>"><div class="metric-top"><span><?= e($label) ?></span><span class="metric-icon"><?= icon($symbol) ?></span></div><strong class="metric-value" data-value="<?= (int) $cards[$key] ?>"><?= number_format($cards[$key], 0, ',', '.') ?></strong><small><?= e($caption) ?></small></a>
<?php endforeach; ?>
</section>
<div class="dashboard-feedback" id="dashboard-feedback" role="status" aria-live="polite"><span id="dashboard-status">Menyiapkan grafik…</span><button class="btn btn-sm btn-light" id="dashboard-retry" hidden>Coba lagi</button></div>
<section class="dashboard-chart-grid" id="dashboard-charts" aria-busy="true">
    <article class="panel movement-panel"><div class="panel-heading"><div><span class="section-kicker">AKTIVITAS</span><h2>Pergerakan inventori</h2><p id="movement-period">Barang masuk dan keluar selama 6 bulan terakhir</p></div><div class="chart-control"><label class="visually-hidden" for="movement-range">Periode pergerakan</label><select class="form-select" id="movement-range"><option value="6">6 bulan terakhir</option><option value="12">12 bulan terakhir</option><option value="ytd">Tahun ini</option></select></div></div><div class="chart-wrap movement-chart"><canvas id="movement-chart" role="img" aria-label="Perbandingan barang masuk dan keluar per bulan"></canvas></div><div class="chart-footnote">Masuk <span class="legend-dot incoming"></span> Keluar <span class="legend-dot outgoing"></span><a href="/reports?type=masuk">Lihat data transaksi <?= icon('arrow') ?></a></div><details class="chart-data"><summary>Lihat angka pergerakan</summary><div class="table-responsive"><table class="table"><thead><tr><th>Bulan</th><th>Masuk</th><th>Keluar</th><th>Net</th></tr></thead><tbody id="movement-data"><?php foreach ($months as $i => $month): ?><tr><td><?= e($month) ?></td><td><?= (int) $series['barang_masuk'][$i] ?></td><td><?= (int) $series['barang_keluar'][$i] ?></td><td><?= $series['barang_masuk'][$i] - $series['barang_keluar'][$i] ?></td></tr><?php endforeach; ?></tbody></table></div></details></article>
    <article class="panel composition-panel"><div class="panel-heading"><div><span class="section-kicker">KOMPOSISI</span><h2>Stok per kategori</h2><p>Proporsi unit tersedia, bukan jumlah SKU</p></div><?= icon('category') ?></div><div class="ring-chart"><canvas id="category-chart" role="img" aria-label="Distribusi unit stok menurut kategori"></canvas><div class="ring-center"><strong><?= number_format($cards['Total stok'], 0, ',', '.') ?></strong><span>unit tersedia</span></div></div><div class="category-legend"><?php foreach ($category as $i => $row): ?><a href="/barang?<?= e(http_build_query(['kategori' => $row['kategori']])) ?>"><span class="legend-dot category-color-<?= $i % 6 ?>"></span><span><?= e($row['kategori']) ?></span><strong><?= number_format((int)$row['total'], 0, ',', '.') ?></strong></a><?php endforeach; ?></div></article>
    <article class="panel distribution-panel"><div class="panel-heading"><div><span class="section-kicker">LOKASI PENYIMPANAN</span><h2>Distribusi gudang</h2><p>Unit dan jenis barang di setiap lokasi</p></div><span class="subtle-badge"><?= count($warehouses) ?> gudang</span></div><div class="chart-wrap warehouse-chart"><canvas id="warehouse-chart" role="img" aria-label="Stok unit per gudang"></canvas></div><div class="warehouse-links"><?php foreach ($warehouses as $row): ?><a href="/barang?gudang_id=<?= (int)$row['id'] ?>"><?= icon('warehouse') ?><span><?= e($row['nama_gudang']) ?><small><?= (int)$row['items'] ?> jenis barang</small></span><strong><?= (int)$row['total'] ?><small>unit</small></strong></a><?php endforeach; ?></div></article>
    <article class="panel health-panel"><div class="panel-heading"><div><span class="section-kicker">KESEHATAN STOK</span><h2>Kesiapan persediaan</h2><p>Status seluruh jenis barang</p></div><?= icon('alert') ?></div><div class="health-overview"><div class="health-ring"><canvas id="health-chart" role="img" aria-label="Jumlah barang aman, rendah, dan habis"></canvas><div class="ring-center"><strong><?= $cards['Total barang'] ? round(100 * ($cards['Total barang'] - $cards['Stok rendah'] - $cards['Stok habis']) / $cards['Total barang']) : 0 ?>%</strong><span>barang aman</span></div></div><div class="health-legend"><?php foreach ($health as $row): ?><a href="/barang?status=<?= e($row['key']) ?>"><span class="stock-status <?= e($row['key']) ?>"><?= ['safe' => '✓','low' => '!','out' => '×'][$row['key']] ?> <?= e($row['label']) ?></span><strong><?= (int)$row['total'] ?></strong><small><?= $cards['Total barang'] ? round(100 * $row['total'] / $cards['Total barang'], 1) : 0 ?>%</small></a><?php endforeach; ?></div></div><div class="health-callout"><strong><?= $cards['Stok rendah'] + $cards['Stok habis'] ?> barang perlu perhatian</strong><p>Prioritaskan stok habis, lalu lengkapi persediaan minimum.</p><a href="/barang?status=attention">Tinjau persediaan <?= icon('arrow') ?></a></div></article>
</section>
<section class="bottom-grid">
    <article class="panel"><div class="panel-heading"><div><span class="section-kicker">RIWAYAT TERKINI</span><h2>Aktivitas inventori</h2><p>Catatan barang masuk dan keluar terbaru</p></div><a href="/reports?type=masuk">Lihat laporan <?= icon('arrow') ?></a></div><div class="table-responsive"><table class="table activity-table"><thead><tr><th>Barang & transaksi</th><th>Jenis</th><th>Jumlah</th><th>Tanggal</th></tr></thead><tbody><?php foreach ($recent as $row): ?><tr><td><a href="/<?= $row['jenis'] === 'Masuk' ? 'barang-masuk' : 'barang-keluar' ?>/<?= (int)$row['id'] ?>"><?= e($row['nama_barang']) ?></a><small class="cell-secondary"><?= e($row['nomor_transaksi']) ?></small></td><td><span class="badge-soft <?= $row['jenis'] === 'Masuk' ? 'green' : 'blue' ?>"><?= icon($row['jenis'] === 'Masuk' ? 'in' : 'out') ?> <?= e($row['jenis']) ?></span></td><td class="quantity-cell"><?= $row['jenis'] === 'Masuk' ? '+' : '−' ?><?= (int)$row['jumlah'] ?></td><td><?= e(date('d M Y', strtotime($row['tanggal']))) ?></td></tr><?php endforeach; ?><?php if (!$recent): ?><tr><td colspan="4" class="empty-state">Belum ada aktivitas. Catat transaksi pertama Anda.</td></tr><?php endif; ?></tbody></table></div></article>
    <article class="panel attention-panel"><div class="panel-heading"><div><span class="section-kicker">TINDAK LANJUT</span><h2>Barang perlu perhatian</h2><p>Stok habis ditampilkan lebih dahulu</p></div><a href="/barang?status=attention">Lihat semua <?= icon('arrow') ?></a></div><?php foreach ($low as $row): $state = ItemUI::health($row); ?><a class="low-item" href="/barang/<?= (int)$row['id'] ?>"><img src="<?= e(ItemUI::photo($row)) ?>" data-fallback="<?= e(ItemUI::placeholder($row['kategori'])) ?>" alt="" loading="lazy"><span class="attention-copy"><strong><?= e($row['nama_barang']) ?></strong><small><?= e($row['kode_barang']) ?> · Minimum <?= (int)$row['stok_minimum'] ?></small><span class="stock-status <?= e($state['key']) ?>"><?= $state['icon'] ?> <?= e($state['label']) ?></span></span><span class="low-stock"><?= (int)$row['stok'] ?><small>unit</small></span></a><?php endforeach; ?><?php if (!$low): ?><div class="empty-state">✓ Semua barang berada di atas stok minimum.</div><?php endif; ?></article>
</section>
