-- Import into an empty database. All stock starts at zero and is derived from transactions.
SET NAMES utf8mb4;
CREATE TABLE roles (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(20) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(150) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL,
 role_id BIGINT UNSIGNED NOT NULL,
 is_active TINYINT NOT NULL DEFAULT 1,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (role_id) REFERENCES roles(id),
 CHECK (is_active IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE gudang (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 kode_gudang VARCHAR(30) NOT NULL UNIQUE,
 nama_gudang VARCHAR(100) NOT NULL,
 lokasi VARCHAR(255) NOT NULL,
 keterangan TEXT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE supplier (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 kode_supplier VARCHAR(30) NOT NULL UNIQUE,
 nama_supplier VARCHAR(100) NOT NULL,
 alamat VARCHAR(255) NOT NULL,
 telepon VARCHAR(30) NOT NULL,
 email VARCHAR(150) NULL,
 keterangan TEXT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE barang (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 kode_barang VARCHAR(30) NOT NULL UNIQUE,
 nama_barang VARCHAR(100) NOT NULL,
 kategori VARCHAR(80) NOT NULL,
 satuan VARCHAR(30) NOT NULL,
 stok INT NOT NULL DEFAULT 0,
 stok_minimum INT NOT NULL DEFAULT 0,
 gudang_id BIGINT UNSIGNED NOT NULL,
 foto VARCHAR(80) NULL,
 deskripsi TEXT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (gudang_id) REFERENCES gudang(id) ON DELETE RESTRICT,
 INDEX idx_barang_kategori (kategori),
 CHECK (stok >= 0), CHECK (stok_minimum >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE barang_masuk (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 nomor_transaksi VARCHAR(50) NOT NULL UNIQUE,
 tanggal DATE NOT NULL,
 barang_id BIGINT UNSIGNED NOT NULL,
 supplier_id BIGINT UNSIGNED NOT NULL,
 jumlah INT NOT NULL,
 keterangan TEXT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (barang_id) REFERENCES barang(id) ON DELETE RESTRICT,
 FOREIGN KEY (supplier_id) REFERENCES supplier(id) ON DELETE RESTRICT,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
 INDEX idx_masuk_tanggal (tanggal),
 CHECK (jumlah > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE barang_keluar (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 nomor_transaksi VARCHAR(50) NOT NULL UNIQUE,
 tanggal DATE NOT NULL,
 barang_id BIGINT UNSIGNED NOT NULL,
 jumlah INT NOT NULL,
 tujuan VARCHAR(255) NOT NULL,
 keterangan TEXT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (barang_id) REFERENCES barang(id) ON DELETE RESTRICT,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
 INDEX idx_keluar_tanggal (tanggal),
 CHECK (jumlah > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE audit_logs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NULL,
 activity VARCHAR(60) NOT NULL,
 description VARCHAR(1000) NOT NULL,
 ip_address VARCHAR(45) NOT NULL,
 user_agent VARCHAR(255) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
 INDEX idx_audit_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE api_tokens (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 token_hash CHAR(64) NOT NULL UNIQUE,
 expires_at DATETIME NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE login_attempts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 identity_hash CHAR(64) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX idx_attempt_identity (identity_hash, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
